### ISSUE TITLE
Issues copying files from iphone/ipad 11.3.1 back to pc

### ISSUE THREAD

**Issue by gummykage** [Cannathea/afc2d-arm64#1]
Using a tool much like ifunbox - imazing whenever I attempt to backup files from my iphone X 256gb running 11.3.1 jailbroken with Electra 1.0.4 the first 12-16 megs will copy and the usb would shutdown and no longer respond.

Copying files to the device is working perfectly.

Backups to itunes are unaffected as backups still complete normally.

**Comment by gummykage** [comment]
BTW i just tested this thoroughly on an ipad mini 4 on 11.3.1 and copying files works on it... Problem appears to be all 3 iphone X's. I've used icleaner to disable everything but afc2 kppless and it still hangs on copying back.

**Comment by ichitaso** [comment]
If you compress it into a zip file, it may work. Other than that, software like iFunBox may not support the new device.
