### ISSUE TITLE
v1.1.3 errors on install

### ISSUE THREAD

**Issue by JEmlay** [Cannathea/afc2d-arm64#14]
new com.cannathea.afc2d-arm64 package extra-installation script subprocess was killed by signal (Abort trap: 6)

Sub-process /usr/libexec/cydia/cydo returned an error code (1)

iPad Pro Gen4  iOS13 (unc0ver)

**Comment by hirakujira** [comment]
Try 1.1.4

**Comment by JEmlay** [comment]
Nope, same problem.  But at least this time around v1.1.2 is still on there and running so it didn't complete trash it.  But it still shows as "half installed".

![IMG_4802](https://user-images.githubusercontent.com/1591895/114906436-deb28f80-9dce-11eb-8ab1-b8e22ea6aa57.PNG)

**Comment by Bullshit-chaos** [comment]
Me too same problem, v1.13 and v1.14.
And i’m not alone.
Why update ? 
Fix it please.

**Comment by Cryptiiiic** [comment]
@hirakujira looks like your toolchain doesn't properly compile for arm64e CPU subtype.

**Comment by Cryptiiiic** [comment]
even xcode 12 fails so something else breaks it, Im sure arm64 only archs is fine

**Comment by hirakujira** [comment]
However my iPhone 12 Pro can install v1.1.4 without any issue. I think the arm64e arch binary doesn't have issue...


Update: yes you are right, I should use Xcode 11 toolchain... the fix is on the way

**Comment by Bullshit-chaos** [comment]
Downgrade version 1.1.2-1 ok for me.
xs Max 13.5 uncover

**Comment by hirakujira** [comment]
Please try v1.1.5-1, which fixed this issue

**Comment by JEmlay** [comment]
Yup, fixed for me, thank you!

**Comment by Bullshit-chaos** [comment]
@hirakujira 😲👍 wow thanks absolutely fantastic good job.
