### ISSUE TITLE
not work with unc0ver 4.3.1 iOS 11.3.1

### ISSUE THREAD

**Issue by profiles** [Cannathea/afc2d-arm64#16]
https://github.com/Cannathea/afc2d-arm64/blob/7e013e72332b4a23f8f22c05cbc4f230738149bd/Tweak.xm#L37

there is no "/usr/share/jailbreak/signcert.p12" file in iOS 11.3.1 jailbreak

**Comment by ichitaso** [comment]
Can you access this URL?
http://appldnld.apple.com
If it is blocked in the hosts file or other files, it will not work.
Also, if SpringBoard has the "/usr/libexec/afc2dSupport" file when it is restarted after installation, it will be enabled if the above is not a problem.

EDIT: I have confirmed that it does not work on iOS 11.4.1. We will fix it later.

**Comment by ichitaso** [comment]
v1.1.6 Fixed this Issue
https://github.com/Cannathea/afc2d-arm64/commit/b7e036a19dcd996a90ff6c23b15d9bef2cef221f
