### ISSUE TITLE
v1.1.7 issues on iOS 16 (16.0.3)

### ISSUE THREAD

**Issue by KirkLandTrip** [Cannathea/afc2d-arm64#18]
I'm using an iPhone X with iOS 16.0.3, jailbroken with Palera1n.
I used the latest files from this repo (the v1.1.7 commit) and created a .deb file by modifying the v1.1.6 one from the release section.

First, Installing using `dpkg -i abc.deb` failed to place `killdaemon` in`/usr/bin`.
I tried to fix that manually by extracting `killdaemon` to that location and setting the owner/permissions like in `postinst`.
I managed to run it and it downloaded & filled `afc2dSupport` then moved it to `afc2d`

Second, it seems that `killdaemon` failed to run `ldid -S/tmp/entitlements_afc2d.xml /usr/libexec/afc2d` because `/tmp` didn't exist on my filesystem.
I created that entitlements file manually and ran `ldid` myself. 
Finally I tried restarting lockdown using /bin/launchctl.
Now I'm just not sure if it's running or not.

I'm using Windows and I might be doing something wrong.
I tried using iFunBox (new version & old version) and it either don't recognize the device is jailbroken (a perquisite for "raw filesystem access") or don't recognize the device at all.
I also tried using the File Explorer but accessing the iPhone via "This PC" still only shows the DCIM folder.

How can I try and interact with afc2d and see if it's running or not?
I know how to open tcp connections over usbmuxd if that helps.

**Comment by ichitaso** [comment]
The Windows version of iFunBox has stopped being updated and we are unable to confirm its operation.
For example, it can be viewed from the iMazing file system.

**Comment by KirkLandTrip** [comment]
OK, I tried iMazing and it doesn't recognize afc2.
![image](https://user-images.githubusercontent.com/112394801/221813650-0983eb77-a986-43e7-8709-af4e96a2e992.png)

I also tried reinstalling the package right from Sileo, it showed version 1.1.7 and finished without errors/warnings.
But iMazing is still returning the same error.

**Comment by KirkLandTrip** [comment]
I ran into this random blog that said I should "just give entitlements to killdaemon and run it" and this time it work.
https://onejailbreak.com/blog/palera1n-jailbreak/
This is the command:
`ldid -s /usr/bin/killdaemon && killdaemon`

This is my iMazing right now:
![image](https://user-images.githubusercontent.com/112394801/221818449-5d02dbf9-7668-4a05-be5b-78badf09f57a.png)

Thanks for the help and your work, ichitaso!

**Comment by fathermrsing** [comment]
> I ran into this random blog that said I should "just give entitlements to killdaemon and run it" and this time it work. https://onejailbreak.com/blog/palera1n-jailbreak/ This is the command: `ldid -s /usr/bin/killdaemon && killdaemon`
> 
> This is my iMazing right now: ![image](https://user-images.githubusercontent.com/112394801/221818449-5d02dbf9-7668-4a05-be5b-78badf09f57a.png)
> 
> Thanks for the help and your work, ichitaso!

It not works in my ios 15.0.1.Is there any other solution?

**Comment by KirkLandTrip** [comment]
When you ran this line did you get this output:
```
My-iPhone:~ root# ldid -s /usr/bin/killdaemon && killdaemon
downloading afcd...
My-iPhone:~ root#
```
?
This is how it looked for me and that meant it worked.
Maybe you also need to update your ldid (also from Sileo)
