### ISSUE TITLE
Rootless for Dopamine Support?

### ISSUE THREAD

**Issue by JEmlay** [Cannathea/afc2d-arm64#20]
I see rootless.h was created two weeks ago however I see no way to install it through normal repos.  Does it need to be updated for Dopamine?

**Comment by ichitaso** [comment]
We would like to create a corresponding one for Dopamine. We have not developed it yet, so please wait a while.

**Comment by JEmlay** [comment]
Awesome, thanks for the update!  I appreciate it.

**Comment by JEmlay** [comment]
Just checking in, it's been over 3 months.  Any new info or ETA?

**Comment by JEmlay** [comment]
Well, if you do ever get to it, it appears you need this entitlement in order to access most important things like the app area:

`<key>com.apple.private.security.container-manager</key>
<true/>`

**Comment by ichitaso** [comment]
Thanks fixed
