### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by 61Halim** [Cannathea/afc2d-arm64#3]
Help pls, it doesn't work on the latest unc0ver and substrate after used rollelectra (Semirestore11)

**Comment by ichitaso** [comment]
It is working 7+ 11.3.1, with uncover 2.1.0 after Rollectra

**Comment by 61Halim** [comment]
Not for some users, where is the problem now? It worked before I did rolllelectra. AFC2 doesn't show the raw on pc

iphone X 11.3.1

**Comment by hirakujira** [comment]
Please try to reinstall ldid. Maybe it's caused by codesign. We can't test by restoring with rolllelectra

**Comment by 61Halim** [comment]
Thanks ldid reinstall doesn't work but downgrade helped me. It works now

**Comment by ichitaso** [comment]
I confirmed it with Apple File Conduit "2" (arm64/KPPLess), and it was not successfully signed with the latest ldid 2.0.1-1.  
<br>
It is normal in the previous version 2.0.0-1.  
https://apt.bingner.com/debs/1443.00/ldid_2:2.0.0-1_iphoneos-arm.deb
