### ISSUE TITLE
Update to arm64e?

### ISSUE THREAD

**Issue by JEmlay** [Cannathea/afc2d-arm64#4]
Not working on my iPad Pro Gen3 A12X (arm64e).  It installs ok but doesn’t work.

Used Chimera to jailbreak.

**Comment by ichitaso** [comment]
In the case of Sileo, the reflection of BigBoss repository is slow, so it is not handled immediately. It works with v1.0.3.  
After installing Link Identity Editor (ldid), it works by installing deb files directly on Sileo.  
http://apt.thebigboss.org/repofiles/cydia/debs2.0/afc2kppless_1.0.3.deb

**Comment by JEmlay** [comment]
Excellent!  Works well.  Thank you very much for your speed, greatly appreciated!
