### ISSUE TITLE
Unable to access RAW file system with unc0ver v4.0.2

### ISSUE THREAD

**Issue by JEmlay** [Cannathea/afc2d-arm64#6]
iPad Pro Gen3 (large)
iPadOS 13.3
unc0ver v4.0.2
AFC2 v1.1
LDID v2.1.2+24497ae-1

Various Windows apps show device as jailed.  Unable to access RAW file system.

**Comment by JEmlay** [comment]
Unc0ver v4.3.1.   Still shows as jailed.

**Comment by JEmlay** [comment]
It also causes springboard to crash and go into safemode.  The crash it totally random.

**Comment by JEmlay** [comment]
3uTools allows me to see the Raw System Files but I can't copy anything to or from it.  It immediately fails then I'm denied access to anything until I unplug the device and plug it back in.

**Comment by ichitaso** [comment]
It is no longer available in iFunBox for Windows. Try iMazing or 3utools.
