### ISSUE TITLE
Not Compatible Unc0ver Jailbrake 13.5

### ISSUE THREAD

**Issue by miguelr4720** [Cannathea/afc2d-arm64#7]
I Install it on my iPhone 11 Pro Max Runing 13.5

but AFC2 does not work with Unc0ver Jailbrake 12.5

i try it so many time doesn’t work and is not showing Var files iFunbox Please fix

**Comment by ichitaso** [comment]
It is no longer available in iFunBox for Windows. Try iMazing or 3utools.
