### ISSUE TITLE
v1.1.1 fails on iOS 12.4 unc0ver due to missing SHA-256 signature [FIX ATTACHED]

### ISSUE THREAD

**Issue by badger200** [Cannathea/afc2d-arm64#9]
[Zip archive.zip](https://github.com/Cannathea/afc2d-arm64/files/5173903/Zip.archive.zip)

I just emailed a more detailed report to the email address Cydia provides to csupport@ cannathea (?) But heres my fix for anyone desperate meanwhile. 

YOU WILL NEED TO RENAME THIS TO A .deb MANUALLY DUE TO GITHUB RULES. Then issue:

`dpkg -i /tmp/archivename.deb`

**Comment by ichitaso** [comment]
To modify the code, please make a pull request.
There is no problem with my iPhone X iOS 12.4 unc0ver v5.2.1

**Comment by badger200** [comment]
Why not simply sign the release with SHA256 as has been standard for years? I don’t know why my devices complain while yours allow SHA1-only signed binaries to slide, but any version of ldid from the past 1-2 years should automatically sign SHA256.
